# Generated by Django 4.2 on 2024-12-05 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=50)),
                ('tipo_area', models.CharField(choices=[('Marketing', 'Marketing'), ('Finanzas', 'Finanzas'), ('Logistica', 'Logística'), ('IT', 'IT'), ('Ventas', 'Ventas'), ('Administrativa', 'Administrativa')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carga', models.CharField(max_length=50)),
                ('relacion', models.CharField(max_length=50)),
                ('grupo_salud', models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('estado_activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrudTrabajadores.area')),
                ('cargas_familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrudTrabajadores.cargafamiliar')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrudTrabajadores.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
